In [ ]:
import pandas as pd

In [ ]:
# Conjunto de datos
datos = {
    "usuario": ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"],
    "edad": [22, 35, 28, 40, 19, 31, 26, 45],
    "ciudad": ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Toluca"],
    "compras_realizadas": [2, 12, 3, 29, 1, 7, 4, 15],
    "activo": [True, False, True, True, False, True, False, True],
    "fecha_registro": ["2026-01-10", "2026-01-12", "2026-01-14", "2026-01-16", "2026-01-18", "2026-01-20", "2026-01-22", "2026-01-24"]
}

In [ ]:
# Creación del DataFrame
df = pd.DataFrame(datos)

In [ ]:
# Mostrar el DataFrame
df

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   2    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-12
2    Martha    28  Guadalajara                   3    True     2026-01-14
3  Carolina    40       Puebla                  29    True     2026-01-16
4     Sofia    19       Cancun                   1   False     2026-01-18
5     Pedro    31       Merida                   7    True     2026-01-20
6     Elena    26      Tijuana                   4   False     2026-01-22
7     Diego    45       Toluca                  15    True     2026-01-24

In [ ]:
#Crear un dataframe con 1000000 de registros
cantidad = 1000000

In [ ]:
#Datos aleatorios
nombres = ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"]
ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Toluca"]
categoria = ["Premium", "Básico", "Premium", "Estándar", "Básico", "Estándar", "Básico", "Premium"]

In [ ]:
import random

In [ ]:
dfMillon = pd.DataFrame({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "edad" : [random.randint(18, 70) for _ in range(cantidad)],
    "salario" : [round(random.uniform(5000, 50000), 2) for _ in range(cantidad)],
    "activo" : [random.choice([True, False]) for _ in range(cantidad)],
    "categoria" : [random.choice(categoria) for _ in range(cantidad)],
    "ciudad" : [random.choice(ciudades) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2000, 2026) for _ in range(cantidad)],
})

In [ ]:
dfMillon

          nombre  edad   salario  activo categoria     ciudad  anio_registro
0       Carolina    41  43376.46    True   Premium     Cancun           2010
1       Carolina    69  11293.46    True  Estándar     Cancun           2010
2           Luis    44  48658.74    True    Básico       CDMX           2016
3          Diego    63  36018.96    True    Básico     Merida           2018
4          Elena    46  20351.80   False   Premium  Monterrey           2005
...          ...   ...       ...     ...       ...        ...            ...
999995      Luis    20   8932.13   False  Estándar     Cancun           2024
999996     Sofia    25  13823.61   False    Básico     Cancun           2007
999997     Sofia    21  16809.94    True  Estándar     Puebla           2011
999998    Martha    23  27395.84   False    Básico       CDMX           2018
999999     Pedro    28  10111.44    True   Premium     Cancun           2016

[1000000 rows x 7 columns]

In [ ]:
dfMillon.dtypes

nombre            object
edad               int64
salario          float64
activo              bool
categoria         object
ciudad            object
anio_registro      int64
dtype: object

In [ ]:
dfMillon.memory_usage(deep=True)

Index                 132
nombre           54124961
edad              8000000
salario           8000000
activo            1000000
categoria        65871490
ciudad           55870205
anio_registro     8000000
dtype: int64

In [ ]:
dfMillon.memory_usage(deep=True).sum() / 1024**2

np.float64(191.56149673461914)